#####
#
# Docker file to build container with Keras and MusicTaggerCRNN
#

FROM tensorflow/tensorflow:latest

MAINTAINER Wei-Yi Cheng

RUN apt-get update && apt-get install -y git-core && \
    rm -rf /var/apt/lists/*

RUN pip install keras pandas h5py && \
    pip install boto3 && \
    rm -rf /root/.cache/pip/*

RUN cd / && git clone https://github.com/Hidysabc/music-bridge.git && \
    cd music-bridge/python && pip install .
